# theme = "ayu_evolve"
# theme = "everforest_dark"
# theme = "kanagawa"
theme = "carbonfox"

[editor]
default-line-ending = "lf"
trim-final-newlines = true
trim-trailing-whitespace = true
color-modes = true # color the mode indicator with different colors depending on the mode itself
line-number = "relative"
# mouse = false
default-yank-register = "+"
cursorline = true
end-of-line-diagnostics = "hint"
# Show tabs bar to list buffers
bufferline = "multiple"
# rulers = [120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = [
  "mode",
  "spinner",
  "version-control",
  "spacer",
  "separator",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",

]
# center = []
# right = [
#   "diagnostics",
#   "workspace-diagnostics",
#   "position",
#   "total-line-numbers",
#   # "position-percentage",
#   # "file-encoding",
#   # "file-line-ending",
#   "file-type",
#   # "register",
#   # "selections",
# ]
# separator = "â”‚"


# [editor.file-picker]
# Enables ignoring hidden files
# hidden = false

# [editor.auto-save]
# focus-lost = true
# after-delay.enable = true
# after-delay.timeout = 2000

# [editor.whitespace]
# render = "all"

# [editor.soft-wrap]
# enable = false

[editor.indent-guides]
render = true
# skip-levels = 0

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "warning"

# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
# S-C-s = "save_selection" # save selection to jumplist, was on ctrl+s
C-q = ":quit"
# C-o = ":open ~/.config/helix/config.toml" # Maps Ctrl-o to opening of the helix config file
# a = "move_char_left" # Maps the 'a' key to the move_char_left command
# w = "move_line_up" # Maps the 'w' key move_line_up
# "C-S-esc" = "extend_line" # Maps Ctrl-Shift-Escape to extend_line
# g = { a = "code_action" } # Maps `ga` to show possible code actions
# "ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode
# "A-x" = "@x<A-d>" # Maps Alt-x to a macro selecting the whole line and deleting it without yanking it
C-right = "move_next_word_start"
C-left = "move_prev_word_end"
S-right = "extend_char_right"
S-left = "extend_char_left"
S-home = ["select_mode", "goto_line_start"]
S-end= ["select_mode", "goto_line_end"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
V = ["select_mode", "extend_to_line_bounds"]
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]
esc = ["collapse_selection", "keep_primary_selection"]
# "*" = ["move_char_right", "move_prev_word_start", "move_next_word_start", "search_selection"]

[keys.insert]
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
C-q = ":quit"
# "A-x" = "normal_mode"     # Maps Alt-X to enter normal mode
# j = { k = "normal_mode" } # Maps `jk` to exit insert mode
C-right = "move_next_word_start"
C-left = "move_prev_word_end"
S-right = "extend_char_right"
S-left = "extend_char_left"

[keys.select]
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
C-q = ":quit"
C-right = "extend_next_word_start"
C-left = "extend_prev_word_end"
S-right = "extend_char_right"
S-left = "extend_char_left"
S-home = ["collapse_selection", "goto_line_start", "extend_char_left"]
S-end= ["collapse_selection", "goto_line_end", "extend_char_right"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
